### ISSUE TITLE
verzoek output als platte kubus

### ISSUE THREAD

**Issue by NThomaes** [ggdatascience/swing_kubusdata_wizard#1]
**Het probleem**
In swing lopen we al langere tijd tegen een aantal problemen aan:
- als je meerdere crossings kiest kan je in swing kruisen binnen een crossing (dus bijvoorbeeld 18-25 jarige man), dit kan zorgen voor kleine groepen. Het liefst zouden we willen dat er maar op 1 kruising gesplitst kan worden. 
- als er bij een bepaalde crossing veel missings zijn, worden deze deelnemers ook niet meer meegenomen in de andere crossings. Dit kan zorgen voor een vertekenend beeld. 
 
**De oplossing**
Vanuit ABF en GGD ZL is er een oplossing bedacht. De platte kubus (https://gezondheidsatlaszl.nl/viewer). Dit zorgt ervoor dat je maar op 1 crossing kan klikken en niet verder kan splitsen op andere crossings. Hiermee wordt ook het probleem van missings in crossings opgelost, want deze tellen niet door in de andere crossings, waardoor de cijfers correct zijn en overeenkomen met het tabellenboek. 
 
**Hoe werkt dit?**
Hiervoor worden alle crossings en het totaal in aparte Excel bestanden geupload in swing. Hiervoor moet ook de wizard meerdere keren runnen voor een set variabelen om de output op deze manier te krijgen. Het zou ons erg helpen als er de optie toegevoegd zou kunnen worden om te kunnen kiezen voor output in de vorm van een platte kubus. Deze output zijn dan dus meerdere excels zijn, voor alle gekozen crossings en het totaal. 
 
**Wat is ons vraag/verzoek?**
Zou het mogelijk zijn om dit in de wizard in te bouwen (output in platte kubus format)?
Ik vermoed dat veel GGD'en die met kubusdata werken dit als een grote verbetering zouden zien.  
 
Als iets niet duidelijk is, mail me gerust (nthomaes@ggdgelderlandzuid.nl)!
Alvast bedankt!

**Comment by stijnimaging** [comment]
Graag wil ik hier op inhaken. 
Effectief hoef je niets te veranderen in de kubusdata wizard. Per crossing kun je een kubus maken met hierin slechts 1 crossing. Dit kan vrij snel gedaan worden door configuratiebestanden te maken per crossing, per gebiedsniveau. Vervolgens doorloop je de "Maak kubus" routine in de wizard en selecteer je telkens het configuratiebestand en de map waarnaar de kubus weggeschreven dient te worden.

De term "platte kubus" wil dus zeggen dat er telkens 1 crossing gebruikt word. De truc binnen Swing is om deze crossings als het ware te stapelen om crossings zichtbaar te maken. Groot voordeel is dat er veel minder missings zijn, doordat er geen kruisingen zijn. De getoonde waarden komen daardoor overeen met het tabellenboek en zijn in zoverre "plat".

Ter info; door ABF is het level "Dimensies" ingebouwd in de Swing viewer. Hiermee kan 1 crossing geselecteerd worden.

**Comment by pieterseinen** [comment]
Ik heb een knop "Platte Kubus" ingebouwd die volgensmij doet wat @NThomaes wil. 

Het is een vrij quick & dirty ingebouwd. Eigenlijk zoals @stijnimaging beschrijft.
Als "Platte Kubus" aanstaat wordt de functie maak_kubusdata() per crossing individueel aangeroepen. Er worden dan bestanden per crossings gemaakt: "kubus_{var}_{crossing}.xlsx"

Nadeel van deze implementatie is dat de popup na het uitvoeren van een configuratie zinloos is geworden. Die zit in de maak_kubusdata() functie ingebouwd en komt dus ook per crossing tevoorschijn. Niet afsluiten na de 1e keer de popup zien dus!
