### ISSUE TITLE
pivot_wider combineert rijen wanneer n_ongewogen gelijk is

### ISSUE THREAD

**Issue by aartdijkstra** [ggdatascience/swing_kubusdata_wizard#2]
Wanneer de data berekend wordt gaat 't (grofweg) door een summarize() en vervolgens een pivot_wider(), waarna alles bij elkaar opgeteld wordt. Dit gaat mis als n_ongewogen in de eerste tabel (voor de pivot) identiek is voor ja en nee. Bijvoorbeeld deze:
![afbeelding](https://github.com/ggdatascience/swing_kubusdata_wizard/assets/125073330/cbd4fae4-a357-475d-82f5-3c3dd5892dbb)

Wanneer vervolgens pivot_wider() wordt uitgevoerd combineert deze de twee rijen tot één geheel, met dus maar 1x n_ongewogen i.p.v. de verwachte 2x:
![afbeelding](https://github.com/ggdatascience/swing_kubusdata_wizard/assets/125073330/a8ceac77-70a3-41b3-8bf9-40eabe21045a)
 
In gevallen waarin een identiek aantal mensen de gevraagde antwoorden heeft gegeven valt daarmee de helft weg in n_ongewogen. De gewogen waardes kloppen wel.

**Comment by pieterseinen** [comment]
Thanks Aart. Dat moet opgelost worden. Helaas niet iets waar ik zelf snel tijd voor zal hebben.

**Comment by aartdijkstra** [comment]
Ik heb een oplossing bedacht en deze als pull request toegevoegd. Helaas wil github niet mooi de wijzigingen laten zien (zie ook https://github.com/ggdatascience/swing_kubusdata_wizard/commit/81489f963c2533c7220887495325f4a3dcc1bd48), dus dan maar even zo. De pivot kan herschreven worden naar twee kolommen, waardoor n_ongewogen ook gesplitst wordt. Deze kan vervolgens handmatig gecombineerd worden: (regel 247)
```
kubus_df <- kubus_df %>%
      pivot_wider(names_from = var, values_from = c(n_gewogen, n_ongewogen), values_fill=0) %>%
      rowwise() %>%
      mutate(n_ongewogen=rowSums(across(starts_with("n_ongewogen")))) %>%
      select(-starts_with("n_ongewogen_")) %>%
      ungroup() %>%
      relocate(n_ongewogen, .before=starts_with("n_gewogen")) %>%
      rename_with(~str_sub(.x, start=11), starts_with("n_gewogen")) %>%
      mutate(geolevel=geolevel, .after=1)
```

De summarize op (nu-)regel 282 is daardoor niet meer nodig, dus dat wordt:
```
kubus_df <- kubus_df %>%
      #Verwijder te lage aantallen
      mutate(across(.cols = c(all_of(namen_variabel_kolommen),"n_ongewogen") ,
                    .fns = Vectorize(verwijder_kleine_aantallen), ongewogen = n_ongewogen))
```

Er zijn verder wat kleine aanpassingen nodig om het verdwijnen van de group_by waarin geolevel werd toegevoegd te compenseren, die zijn allemaal verwerkt in de pull request.

Ik heb de resultaten bij ons gecontroleerd op de dataset waar 't fout liep, maar kijk vooral ook even bij jullie!

**Comment by pieterseinen** [comment]
Super! Dankjewel. Een test gedaan met fictieve data. Werkt  goed.
