### ISSUE TITLE
Error bij het maken van platte kubus data

### ISSUE THREAD

**Issue by fleurlr** [ggdatascience/swing_kubusdata_wizard#3]
Hallo wij krijgen de volgende error bij het maken van platte kubus data:

Warning: Error in maak_kubusdata: unused argument (bestandslabel_platte_kubus = glue("_{i}"))

Als wij deze regel uitzetten komt er wel een output. Hopelijk kan iemand ons helpen.

**Comment by pieterseinen** [comment]
was een fout die nu is opgelost. stond een verouderde versie van code van global.R online waarbij geen rekening werd gehouden met de optie een platte kubus te maken.
